#!/home/ilab/python2.7.11/bin/python

#-----------------------------------------------------------------------------
#  Copyright (C) 2015  The iLab Development Team
#
#  version = 3.0
#  Distributed under the terms of the Cisco Systems Inc. The full license is
#  in the file COPYING, distributed as part of this software.
#-----------------------------------------------------------------------------

import os
import time
import re
import sys

from optparse import OptionParser
from datetime import datetime, date, timedelta

import parseLoader as pLoad 

if __name__=='__main__':
    usage = "usage: %prog [--add | --update | --remove | --show | --hold | --release | --poweron] arg1\n"
    usage += "\nGitlab - http://gitlab.cisco.com/rkorlepa/iLab.git"
    parser = OptionParser(usage=usage)
    parser.add_option("--add", metavar="/<path>/switch.json",  action="store", dest="addfile", type="string", help="JSON file location of the switches to add to db")
    parser.add_option("--update", metavar="/<path>/switch.json",  action="store", dest="updatefile", type="string", help="JSON file location of the switches to update")
    parser.add_option("--remove", metavar="flute",  action="store", dest="remove_sw", type="string", help="Switch name to remove from db")
    parser.add_option("--show", metavar="flute", action="store", dest="show_sw_name", type="string", help="Show details of the switch in db")
    parser.add_option("--hold", metavar="flute", action="store", dest="hold_sw_name", type="string", help="Hold the switch i.e. for sanity/poweroff")
    parser.add_option("--release", metavar="flute", action="store", dest="release_sw_name", type="string", help="Release the switch i.e. for sanity/poweroff")
    parser.add_option("--poweron", metavar="flute", action="store", dest="poweron_sw_name", type="string", help="Power on the switch")
    options,args = parser.parse_args()
    
    if options.addfile != None:
        if options.updatefile != None or options.remove_sw != None or \
           options.show_sw_name != None or options.hold_sw_name != None or \
           options.release_sw_name != None or options.poweron_sw_name != None:
            print "Error you cannot pass two options together"
        else:
            pLoad.insertSwitch(options.addfile)

    if options.updatefile != None:
        if options.addfile != None or options.remove_sw != None or \
           options.show_sw_name != None or options.hold_sw_name != None or \
           options.release_sw_name != None or options.poweron_sw_name != None:
            print "Error you cannot pass two options together"
        else:
            pLoad.updateSwitch(options.updatefile)

    if options.remove_sw != None:
        if options.addfile != None or options.updatefile != None or \
           options.show_sw_name != None or options.hold_sw_name != None or \
           options.release_sw_name != None or options.poweron_sw_name != None:
            print "Error you cannot pass two options together"
        else:
            pLoad.removeSwitch(options.remove_sw) 

    if options.show_sw_name != None:
        if options.addfile != None or options.updatefile != None or \
           options.remove_sw != None or options.hold_sw_name != None or \
           options.release_sw_name != None or options.poweron_sw_name != None:
            print "Error you cannot pass two options together"
        else:
            pLoad.showSwitch(options.show_sw_name)

    if options.hold_sw_name != None:
        if options.addfile != None or options.updatefile != None or \
           options.remove_sw != None or options.show_sw_name != None or \
           options.release_sw_name != None or options.poweron_sw_name != None:
            print "Error you cannot pass two options together"
        else:
            pLoad.holdSwitch(options.hold_sw_name)

    if options.release_sw_name != None:
        if options.addfile != None or options.updatefile != None or \
        options.remove_sw != None or options.show_sw_name != None or \
        options.hold_sw_name != None or options.poweron_sw_name != None:
            print "Error you cannot pass two options together"
        else:
            pLoad.releaseSwitch(options.release_sw_name)

    if options.poweron_sw_name != None:
        if options.addfile != None or options.updatefile != None or \
        options.remove_sw != None or options.show_sw_name != None or \
        options.hold_sw_name != None or options.release_sw_name != None:
            print "Error you cannot pass two options together"
        else:
            pLoad.poweronSwitch(options.poweron_sw_name)
